import type { Metadata } from "next";
import Link from "next/link";
import { PublicPageShell, publicCardClass, publicPrimaryLinkClass } from "@/components/public-page-shell";
import { STANDARD_SPACE_RETENTION, EXTENSION_FILE_RETENTION } from "@/lib/sharing-copy";

export const metadata: Metadata = {
  title: "Sharing Help",
  description: "Help with Woff sharing links, notes, uploads, exports, room ownership, recovery, and temporary file availability.",
  alternates: { canonical: "/help" },
};

const topics = [
  { id: "start", title: "Create and share a room", paragraphs: ["Select Start sharing to create a free room. Send a message, choose Note, or add photos and files. Wait for an upload to finish before asking someone to download it.", "New rooms can be joined with their four-digit code. Use Share to copy the link or show a QR code. The owner can change the code, close code access, or set a time limit. Anyone with an enabled code or valid invitation can join without signing up."] },
  { id: "notes", title: "Notes and private notes", paragraphs: ["Choose Note in the composer to open the rich editor. Only the note's creator can edit it. Other participants can read a shared note and contribute their own messages or notes in a sharing room.", "Making a note private restricts it to its creator. It is not a recipient password feature. If you want someone to read the note, make it shared again. Previously downloaded copies cannot be withdrawn."] },
  { id: "room-names", title: "Pro room names and URLs", paragraphs: ["Pro senders can open Share → Room name & URL → Edit, or use Name & URL on a dashboard room card. A room name can contain letters, spaces and your language. For the URL, choose 3–40 characters with at least one English letter; numbers and single hyphens are allowed, such as woff.space/sabbir-files. Addresses must be available; site pages are reserved. You can also keep a four-digit room code.", "Changing the URL stops the old direct URL from working. Existing members and invitation links keep their access, and the room's time limit stays the same. Closing code access also closes new joins through a custom URL. If Pro ends, the current URL stays available, but editing the name or choosing another custom URL requires Pro."] },
  { id: "uploads", title: "File limits and upload retries", paragraphs: ["Files can be up to 50 MiB each, with up to 20 files in one batch. Your room and owner storage allowances include files, note images, drawings, and pending uploads. Review current allowances on the pricing page.", "Keep the tab open during upload. A failed batch offers Retry or cancellation. Check your internet connection and available allowance; reduce the batch if needed. A completed batch appears together, so recipients do not see only part of it."] },
  { id: "expiry", title: "Availability and expiry", paragraphs: [STANDARD_SPACE_RETENTION, "If the owner sets a time limit, the room shows it in its top bar. New messages and downloads do not move a chosen deadline. Download files and export notes before it ends; expired rooms become unavailable and are scheduled for deletion.", "Keep a copy of anything important. A recovery key cannot restore deleted content. " + EXTENSION_FILE_RETENTION] },
  { id: "ownership", title: "Ownership and recovery", paragraphs: ["Anonymous ownership belongs to the browser session that created the room. Keep the recovery key in a safe place so you can restore creator controls if the session is lost. The recovery key is different from a reader's invitation link.", "Use Recover ownership in room settings with your recovery key. Never send the key to a recipient. Optional sender accounts, when available, let you manage owned rooms across devices; a room recovery key does not restore a paid account or subscription."] },
  { id: "export", title: "Save your own copy", paragraphs: ["Use Download on a file or Download all for an available file batch. Large ZIPs take time and memory to prepare; download files individually if your device struggles.", "In a note, open its options menu and choose Export for Markdown, plain text, or Print / PDF. The browser's print dialog lets you save a PDF. Check the result, including images and non-English text, before you close the room.", "Download all in the activity list exports notes as HTML with embedded images. Open the HTML in a browser to print it or save a PDF. A ZIP has a 128 MiB browser limit; export images individually if a note exceeds its 64 MiB image limit. A missing image cancels the export and shows an error."] },
  { id: "connection", title: "Connection and draft recovery", paragraphs: ["If the room is connecting, check your connection and reload once it returns. A room may also have expired or its access may have been closed. Ask the sender for a current link if the invitation no longer works.", "The note editor keeps local recovery drafts when it can. If it shows a save error or a draft banner, keep the tab open, export your changes, and reconnect or restore the draft. A saved status confirms saving in the room; it does not promise permanent availability."] },
  { id: "billing", title: "Accounts, billing, and support", paragraphs: ["The pricing page states whether the Pro pilot is open. When a subscription is available, use Account for its billing controls. Recipients can open a delivery without buying a plan.", "For an account, billing, upload, or abuse issue, contact support. Include the error and time it occurred. Do not email passwords, recovery keys, private file contents, or full invitation links unless support specifically needs a limited diagnostic reference."] },
];

export default function HelpPage() {
  return <PublicPageShell eyebrow="Sharing help" title="Get your files" accent="where they need to go" description="A practical guide to sharing, keeping your own copies, and finding your way back to a room.">
    <nav aria-label="Help topics" className="mb-10 flex flex-wrap justify-center gap-3">
      {topics.map((topic) => <a key={topic.id} href={`#${topic.id}`} className="rounded-full border px-4 py-2 text-sm font-medium text-muted-foreground hover:border-orange-500/40 hover:text-foreground">{topic.title}</a>)}
    </nav>
    <div className="space-y-6">{topics.map((topic) => <section key={topic.id} id={topic.id} className={`${publicCardClass} scroll-mt-24`}>
      <h2 className="mb-4 text-xl font-bold">{topic.title}</h2>
      <div className="space-y-3">{topic.paragraphs.map((paragraph) => <p key={paragraph} className="text-sm leading-7 text-muted-foreground">{paragraph}</p>)}</div>
    </section>)}</div>
    <div className="mt-10 flex flex-wrap justify-center gap-4"><Link href="/new" className={publicPrimaryLinkClass}>Start sharing</Link><Link href="/recover" className="inline-flex items-center px-4 text-sm font-semibold text-orange-600 dark:text-orange-400">Recover room ownership</Link><Link href="/pricing" className="inline-flex items-center px-4 text-sm font-semibold text-orange-600 dark:text-orange-400">Plans and limits</Link><Link href="/contact" className="inline-flex items-center px-4 text-sm font-semibold text-orange-600 dark:text-orange-400">Contact support</Link></div>
  </PublicPageShell>;
}
